### ISSUE TITLE
Versionierung der Releases

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/coalbase-infrastructure#7]

**Comment by JannIntveen** [comment]
Semantic Versioning

https://semver.org/

**Comment by stefanbente** [comment]
Bitte als Programming Convention in die Doku (in coalbase-doku)

**Comment by stefanbente** [comment]
Issue moved to [Archi-Lab/coalbase-documentation #19](https://github.com/Archi-Lab/coalbase-documentation/issues/19) via [**ZenHub**](https://www.zenhub.com/)
